import Link from "next/link";
import { invoiceDetail } from "@/lib/invoices/server";
import { formatBusinessDate,formatMoney } from "@/lib/billing/model";
import { statuses,units } from "@/lib/invoices/model";
import { FinalizeInvoice } from "@/components/invoices/finalize-invoice";
export default async function InvoicePage({params}:{params:Promise<{id:string}>}) {
  const {invoice:v,items,totals} = await invoiceDetail((await params).id);
  const address = [v.billing_address_line1_snapshot,v.billing_address_line2_snapshot,[v.billing_city_snapshot,v.billing_state_snapshot,v.billing_postal_code_snapshot].filter(Boolean).join(", "),v.billing_country_snapshot].filter(Boolean);
  return <><Link href="/invoices" className="text-sm font-medium text-cyan-700">← Invoices</Link><div className="mb-6 mt-4 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-tight">Invoice #{v.invoice_number}</h1><span className="rounded-md bg-slate-200 px-3 py-1 text-sm font-medium">{statuses[v.status as keyof typeof statuses]??v.status}</span></div>
    <article className="min-w-0 rounded-xl border border-slate-200 bg-white p-5 sm:p-8"><div className="grid gap-6 border-b border-slate-200 pb-6 sm:grid-cols-2"><section className="min-w-0 break-words"><h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Bill to</h2><p className="font-semibold">{v.company_name_snapshot}</p>{[v.primary_contact_name_snapshot,v.email_snapshot,v.phone_snapshot,...address].filter(Boolean).map((value,i)=><p key={i} className="mt-1 text-sm text-slate-600">{value}</p>)}</section><dl className="space-y-3 text-sm sm:text-right"><div><dt className="text-slate-500">Issue date</dt><dd className="mt-1 font-medium">{formatBusinessDate(v.issue_date)}</dd></div><div><dt className="text-slate-500">Due date</dt><dd className="mt-1 font-medium">{formatBusinessDate(v.due_date)}</dd></div></dl></div>
      <section aria-label="Invoice line items" className="divide-y divide-slate-100">{items.map(i=><div key={i.id} className="grid min-w-0 gap-3 py-5 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><h2 className="whitespace-pre-wrap break-words font-medium">{i.description}</h2><p className="mt-1 text-sm text-slate-500">{new Intl.NumberFormat("en-US",{maximumFractionDigits:8}).format(i.quantity)} × {units[i.unit as keyof typeof units]??i.unit} · {formatMoney(i.unit_rate)}</p></div><div className="sm:text-right"><p className="break-all font-medium tabular-nums">{formatMoney(i.amount)}</p>{i.tax_amount!==0&&<p className="mt-1 text-sm text-slate-500">Tax {formatMoney(i.tax_amount)}</p>}</div></div>)}</section>
      <dl className="ml-auto max-w-sm space-y-3 border-t border-slate-200 pt-5 text-sm">{[["Subtotal",totals.subtotal],["Tax",totals.tax_amount],["Total",totals.total]].map(([label,value])=><div key={label} className={`flex justify-between gap-4 ${label==="Total"?"text-xl font-semibold":"text-slate-600"}`}><dt>{label}</dt><dd className="min-w-0 break-all text-right tabular-nums">{formatMoney(value as number)}</dd></div>)}</dl>
      {(v.notes||v.terms)&&<div className="mt-8 grid gap-6 border-t border-slate-100 pt-6 sm:grid-cols-2">{[["Notes",v.notes],["Terms",v.terms]].map(([label,value])=>value&&<section key={label} className="min-w-0"><h2 className="text-sm font-semibold">{label}</h2><p className="mt-2 whitespace-pre-wrap break-words text-sm text-slate-600">{value}</p></section>)}</div>}
    </article>{v.status==="draft"&&<FinalizeInvoice id={v.id}/>}</>;
}
