begin;
create function pg_temp.pay_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;end $$;
create function pg_temp.pay_reject(command text) returns void language plpgsql as $$begin
 begin execute command;exception when others then return;end;
 raise exception 'Unexpected success: %',command;
end $$;
set local role authenticated;
do $$
declare c uuid;v uuid;r record;p1 uuid;p2 uuid;p3 uuid;k uuid:=gen_random_uuid();n integer;bad text;pr record;status_before text;
begin
 perform pg_temp.pay_assert((select count(*)=1 and bool_and(cash_enabled and check_enabled and card_enabled) from public.payment_settings),'Seeded singleton defaults');
 perform pg_temp.pay_reject('select public.update_payment_settings(false,false,false)');
 perform pg_temp.pay_reject('update public.payment_settings set cash_enabled=false,check_enabled=false,card_enabled=false');
 perform pg_temp.pay_reject('delete from public.payment_settings');
 perform pg_temp.pay_reject('insert into public.payment_settings(singleton) values(false)');
 insert into public.customers(company_name) values('Payment fixture') returning id into c;
 select invoice_id,invoice_number into v,n from public.create_manual_invoice(c,'2026-09-10','[{"description":"Invoice","quantity":1,"unit":"flat","unit_rate":500}]',gen_random_uuid());
 perform pg_temp.pay_assert((select payment_status='unpaid' and balance_due=500 and payment_count=0 and latest_payment_date is null from public.invoice_payment_summary where invoice_id=v),'Initial unpaid balance');
 update public.invoices set status='ready' where id=v;
 select * into r from public.record_invoice_payment(v,100,'2026-09-10','cash',k,'  Receipt 1  ','  note  ');p1:=r.payment_id;
 perform pg_temp.pay_assert(r.amount_paid=100 and r.balance_due=400 and r.payment_status='partially_paid' and r.payment_count=1,'Cash partial payment against Ready');
 select * into r from public.record_invoice_payment(v,100.00,'2026-09-10','cash',k,'Receipt 1','note');
 perform pg_temp.pay_assert(r.payment_id=p1 and r.payment_count=1,'Normalized exact retry');
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,101,''2026-09-10'',''cash'',%L,''Receipt 1'',''note'')',v,k));
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,100,''2026-09-11'',''cash'',%L,''Receipt 1'',''note'')',v,k));
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,100,''2026-09-10'',''check'',%L,''Receipt 1'',''note'')',v,k));
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,100,''2026-09-10'',''cash'',%L,''Different reference'',''note'')',v,k));
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,100,''2026-09-10'',''cash'',%L,''Receipt 1'',''Different note'')',v,k));
 update public.invoices set status='ready' where id=v;
 select * into r from public.record_invoice_payment(v,150,'2026-09-11','check',gen_random_uuid(),'Check #1024');p2:=r.payment_id;
 perform pg_temp.pay_assert(r.amount_paid=250 and r.balance_due=250 and r.payment_count=2,'Check payment against Ready');
 update public.invoices set status='sent' where id=v;
 select * into r from public.record_invoice_payment(v,250,'2026-09-12','card',gen_random_uuid());p3:=r.payment_id;
 perform pg_temp.pay_assert(r.amount_paid=500 and r.balance_due=0 and r.payment_status='paid' and r.payment_count=3 and r.latest_payment_date='2026-09-12','Card, exact remaining full payment against Sent');
 perform pg_temp.pay_assert((select status='sent' and invoice_number=n from public.invoices where id=v),'Payments do not change workflow or number');
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,1,''2026-09-12'',''cash'',%L)',v,gen_random_uuid()));
 perform public.update_payment_settings(true,true,false);
 perform pg_temp.pay_assert((select amount_paid=500 and payment_count=3 from public.invoice_payment_summary where invoice_id=v),'Disabling Card preserves history');
 select request_id into k from public.invoice_payments where id=p3;
 select * into r from public.record_invoice_payment(v,250,'2026-09-12','card',k);
 perform pg_temp.pay_assert(r.payment_id=p3 and r.payment_count=3,'Retry after method disabled');
 perform public.void_invoice_payment(p3,'Incorrect record');
 perform public.void_invoice_payment(p3,'Incorrect record');
 perform pg_temp.pay_assert((select amount_paid=250 and balance_due=250 and payment_status='partially_paid' and payment_count=2 and latest_payment_date='2026-09-11' from public.invoice_payment_summary where invoice_id=v),'Voiding removes contribution and recalculates latest valid date');
 select * into r from public.record_invoice_payment(v,250,'2026-09-12','card',k);
 perform pg_temp.pay_assert(r.payment_id=p3 and r.payment_voided_at is not null and r.amount_paid=250,'Voided retry never resurrects payment');
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,10,''2026-09-12'',''card'',%L)',v,gen_random_uuid()));
 perform pg_temp.pay_reject(format('insert into public.invoice_payments(invoice_id,amount,payment_date,payment_method,request_id) values(%L,10,''2026-09-12'',''card'',%L)',v,gen_random_uuid()));
 perform pg_temp.pay_reject(format('update public.invoice_payments set amount=1 where id=%L',p1));
 perform pg_temp.pay_reject(format('update public.invoice_payments set reference=''Changed'' where id=%L',p1));
 perform pg_temp.pay_reject(format('update public.invoice_payments set voided_at=null,void_reason=null where id=%L',p3));
 perform pg_temp.pay_reject(format('delete from public.invoice_payments where id=%L',p1));
 perform pg_temp.pay_reject(format('select public.void_invoice_payment(%L,'' '')',p1));
 foreach bad in array array['0','-1','NaN','Infinity','-Infinity','1.001','10000000000'] loop
  perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,%L::numeric,''2026-09-10'',''cash'',%L)',v,bad,gen_random_uuid()));
  perform pg_temp.pay_reject(format('insert into public.invoice_payments(invoice_id,amount,payment_date,payment_method,request_id) values(%L,%L::numeric,''2026-09-10'',''cash'',%L)',v,bad,gen_random_uuid()));
 end loop;
 foreach bad in array array['infinity','-infinity'] loop
  perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,1,%L::date,''cash'',%L)',v,bad,gen_random_uuid()));
 end loop;
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,1,''2026-09-10'',''ach'',%L)',v,gen_random_uuid()));
 -- A legitimate atomic edit replaces lines without locking the invoice by status.
 select * into pr from public.preview_invoice_edit(v,'2026-09-10');
 perform public.update_composed_invoice(v,'2026-09-10','2026-09-10',gen_random_uuid(),pr.revision,'{}','[{"description":"Edited paid invoice","quantity":1,"unit":"flat","unit_rate":300}]');
 set constraints all immediate;set constraints all deferred;
 perform pg_temp.pay_assert((select invoice_total=300 and amount_paid=250 and balance_due=50 from public.invoice_payment_summary where invoice_id=v),'Atomic edit safely preserves payments and recomputes balance');
 select * into pr from public.preview_invoice_edit(v,'2026-09-10');
 begin
  perform public.update_composed_invoice(v,'2026-09-10','2026-09-10',gen_random_uuid(),pr.revision,'{}','[{"description":"Below payments","quantity":1,"unit":"flat","unit_rate":200}]');
  set constraints all immediate;
  raise exception using errcode='ZX001',message='Unexpected below-paid edit';
 exception when check_violation then null;end;
 perform pg_temp.pay_assert((select invoice_total=300 and amount_paid=250 from public.invoice_payment_summary where invoice_id=v),'Rejected edit rolls back its lines and history');
 select * into r from public.record_invoice_payment(v,50,'2026-09-13','cash',gen_random_uuid());
 perform pg_temp.pay_assert(r.payment_status='paid' and r.balance_due=0,'Exact remaining amount after edit');
 update public.invoices set status='void',void_reason='Invoice void fixture' where id=v;
 perform pg_temp.pay_assert((select invoice_status='void' and amount_paid=300 and payment_count=3 from public.invoice_payment_summary where invoice_id=v),'Void preserves valid payments and historical summary');
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,1,''2026-09-10'',''cash'',%L)',v,gen_random_uuid()));
 perform public.void_invoice_payment(p1,'Correct historical payment');
 perform pg_temp.pay_assert((select count(*)=4 from public.invoice_payments where invoice_id=v),'All payment history preserved, including two voided records');
 -- Zero-total invoice has nothing due, no payment is permitted.
 select invoice_id into v from public.create_manual_invoice(c,'2026-09-10','[{"description":"No charge","quantity":1,"unit":"flat","unit_rate":0}]',gen_random_uuid());
 perform pg_temp.pay_assert((select invoice_total=0 and amount_paid=0 and balance_due=0 and payment_status='paid' from public.invoice_payment_summary where invoice_id=v),'Zero total has zero balance');
 perform pg_temp.pay_reject(format('select public.record_invoice_payment(%L,0.01,''2026-09-10'',''cash'',%L)',v,gen_random_uuid()));
end $$;
set constraints all immediate;
reset role;
select pg_temp.pay_assert(not has_table_privilege('authenticated','public.invoice_payments','DELETE') and not has_table_privilege('authenticated','public.payment_settings','INSERT,DELETE'),'Minimal grants');
select pg_temp.pay_assert(has_table_privilege('authenticated','public.invoice_payments','SELECT') and has_table_privilege('authenticated','public.invoice_payments','INSERT') and has_table_privilege('authenticated','public.invoice_payments','UPDATE'),'Authenticated ledger read/record/correction grants');
select pg_temp.pay_assert(not has_function_privilege('anon','public.record_invoice_payment(uuid,numeric,date,text,uuid,text,text)','EXECUTE') and not has_function_privilege('service_role','public.record_invoice_payment(uuid,numeric,date,text,uuid,text,text)','EXECUTE'),'RPC execution explicitly authenticated only');
select pg_temp.pay_assert((select reloptions @> array['security_invoker=true'] from pg_class where oid='public.invoice_payment_summary'::regclass),'Summary security invoker');
select set_config('nexa.test_invoice',(select invoice_id::text from public.invoice_payments limit 1),true);
create policy payment_test_invoice_deny on public.invoices as restrictive for select to authenticated using(false);
set local role authenticated;
select pg_temp.pay_assert(not exists(select from public.invoice_payment_summary) and not exists(select from public.invoice_payments),'Summary and history honor caller invoice RLS');
select pg_temp.pay_reject(format('select public.record_invoice_payment(%L,1,''2026-09-10'',''cash'',gen_random_uuid())',current_setting('nexa.test_invoice')));
reset role;
set local role anon;
select pg_temp.pay_reject('select * from public.payment_settings');
select pg_temp.pay_reject('select * from public.invoice_payments');
select pg_temp.pay_reject('select * from public.invoice_payment_summary');
select pg_temp.pay_reject('select public.update_payment_settings(true,true,true)');
select pg_temp.pay_reject('select public.record_invoice_payment(gen_random_uuid(),1,''2026-09-10'',''cash'',gen_random_uuid())');
select pg_temp.pay_reject('select public.void_invoice_payment(gen_random_uuid(),''Correction'')');
reset role;
rollback;
