import Link from "next/link";
import { quoteDetail } from "@/lib/quotes/server";
import { customerClient } from "@/lib/customers/server";
import { quoteContact,quoteLines,quoteStatus,quoteStatuses } from "@/lib/quotes/model";
import { businessDate,formatBusinessDate,formatMoney } from "@/lib/billing/model";
import { QuoteActions } from "@/components/quotes/quote-actions";
export default async function QuotePage({params}:{params:Promise<{id:string}>}) {
 const q=await quoteDetail((await params).id);const today=businessDate();
 let invoiceNumber:number|undefined;
 if(q.converted_invoice_id){const client=await customerClient();const r=await client.from("invoices").select("invoice_number").eq("id",q.converted_invoice_id).single();if(r.error)throw new Error("Unable to load converted invoice.");invoiceNumber=r.data.invoice_number;}
 return <div className="mx-auto max-w-4xl"><Link href="/quotes" className="text-sm font-medium text-cyan-700">← Quotes</Link>
 <header className="my-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-tight">Quote Q-{q.quote_number}</h1><span className="rounded-md bg-slate-100 px-3 py-1 text-sm font-medium">{quoteStatuses[quoteStatus(q,today) as keyof typeof quoteStatuses]}</span></div><div className="flex flex-wrap gap-3"><a href={`/quotes/${q.id}/pdf`} target="_blank" rel="noopener noreferrer" className="rounded-lg border border-slate-300 bg-white px-5 py-3 font-semibold">View PDF<span className="sr-only"> (opens in a new tab)</span></a>{q.status==="draft"&&!q.converted_invoice_id&&<Link href={`/quotes/${q.id}/edit`} className="rounded-lg border border-slate-300 bg-white px-5 py-3 font-semibold">Edit Quote</Link>}</div></header>
 {q.converted_invoice_id&&<p className="mb-5 rounded-lg border border-cyan-200 bg-cyan-50 p-4 text-sm">Converted to <Link className="font-semibold text-cyan-800 underline" href={`/invoices/${q.converted_invoice_id}`}>Invoice #{invoiceNumber}</Link>. The accepted quote is preserved.</p>}
 <article className="min-w-0 rounded-xl border border-slate-200 bg-white p-5 sm:p-8"><div className="grid gap-6 border-b border-slate-200 pb-6 sm:grid-cols-2"><section className="min-w-0 break-words"><h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Prepared for</h2><p className="font-semibold">{q.company_name_snapshot}</p>{quoteContact(q).map((v,i)=><p key={i} className="mt-1 text-sm text-slate-600">{v}</p>)}</section><dl className="space-y-3 text-sm sm:text-right"><div><dt className="text-slate-500">Quote date</dt><dd className="mt-1 font-medium">{formatBusinessDate(q.quote_date)}</dd></div>{q.expiration_date&&<div><dt className="text-slate-500">Valid through</dt><dd className="mt-1 font-medium">{formatBusinessDate(q.expiration_date)}</dd></div>}</dl></div>
 <section aria-label="Quote line items" className="mt-5">{quoteLines(q.items).map((i,index)=><div key={index} className="grid min-w-0 grid-cols-3 gap-3 border-b border-slate-100 py-5 sm:grid-cols-[minmax(0,1fr)_6rem_7rem_8rem]"><h2 className="col-span-3 min-w-0 whitespace-pre-wrap break-words font-medium sm:col-span-1">{i.description}</h2><div className="text-sm sm:text-right"><span className="block text-xs text-slate-500">Quantity / unit</span>{i.quantity} {i.unit}</div><div className="text-right text-sm"><span className="block text-xs text-slate-500">Rate</span>{formatMoney(Number(i.unit_rate))}</div><div className="text-right text-sm"><span className="block text-xs text-slate-500">Amount</span>{formatMoney(Number(i.amount))}</div></div>)}</section>
 <dl className="ml-auto mt-5 max-w-sm space-y-3">{[["Subtotal",q.subtotal],["Total",q.total]].map(([label,value])=><div key={label} className="flex justify-between gap-3"><dt>{label}</dt><dd className="font-semibold tabular-nums">{formatMoney(Number(value))}</dd></div>)}</dl>
 <div className="mt-6 grid gap-6 sm:grid-cols-2">{[["Notes",q.notes],["Terms",q.terms]].map(([label,value])=>value&&<section key={label} className="min-w-0"><h2 className="text-sm font-semibold">{label}</h2><p className="mt-2 whitespace-pre-wrap break-words text-sm text-slate-600">{value}</p></section>)}</div></article>
 <QuoteActions key={q.revision} quote={q} today={today}/></div>;
}
