import Link from "next/link";
import type { getInvoiceReport } from "@/lib/invoices/report-server";
import { reportSorts,reportUrl } from "@/lib/invoices/report";
import { statuses } from "@/lib/invoices/model";
import { paymentStatuses } from "@/lib/payments/model";
import { formatMoney,formatBusinessDate } from "@/lib/billing/model";
const focus="focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-700";
const input="mt-1 block w-full min-w-0 rounded-lg border border-slate-300 bg-white h-8 px-2 py-1 text-xs text-slate-900";
const date=(value:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`));
const workflowLabel=(value:string)=>statuses[value as keyof typeof statuses];
const paymentLabel=(value:string)=>paymentStatuses[value as keyof typeof paymentStatuses];
export function InvoiceReportView({data}:{data:Awaited<ReturnType<typeof getInvoiceReport>>}) {
  const {filters:{values},customers,customerMessage,report,message}=data;
  const selectedMissing=values.customer&&!customers.some(c=>c.id===values.customer);
  return <div className="@container min-w-0 max-w-full space-y-4 [overflow-wrap:anywhere]">
    <header className="flex min-w-0 flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Invoices</h1><p className="mt-2 text-sm text-slate-600">Invoice history, payments, and outstanding balances.</p></div><Link className={`shrink-0 rounded-lg bg-cyan-400 px-4 py-2 text-sm font-semibold ${focus}`} href="/invoices/new">New Invoice</Link></header>
    <form key={reportUrl(values,Number(values.page)||1)} action="/invoices" method="get" autoComplete="off" aria-label="Invoice filters" className="rounded-lg border border-slate-200 bg-white p-3">
      <div className="grid gap-2 sm:grid-cols-2 @min-[680px]:grid-cols-[minmax(0,2fr)_minmax(0,1fr)_minmax(0,1.2fr)_minmax(0,1.6fr)]">
        <label className="min-w-0 text-[11px] font-medium text-slate-600">Search<input className={input} type="search" name="q" maxLength={500} defaultValue={values.q} placeholder="Search invoice # or customer"/></label>
        <label className="min-w-0 text-[11px] font-medium text-slate-600">Workflow<select className={input} name="workflow" defaultValue={values.workflow}><option value="">All</option>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
        <label className="min-w-0 text-[11px] font-medium text-slate-600">Payment status<select className={input} name="payment" defaultValue={values.payment}><option value="">All</option>{Object.entries(paymentStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
        <label className="min-w-0 text-[11px] font-medium text-slate-600">Customer<select className={input} name="customer" defaultValue={values.customer}><option value="">All customers</option>{selectedMissing&&<option value={values.customer}>Selected customer unavailable</option>}{customers.map(c=><option key={c.id} value={c.id}>{`${c.company_name}${c.is_active?"":" (Archived)"}`}</option>)}</select></label>
      </div>
      <div className="mt-2 grid gap-2 sm:grid-cols-2 @min-[680px]:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,1.15fr)_auto]">
        <label className="min-w-0 text-[11px] font-medium text-slate-600">From<input className={input} type="date" name="from" aria-label="Issue date From" defaultValue={values.from||""}/></label>
        <label className="min-w-0 text-[11px] font-medium text-slate-600">To<input className={input} type="date" name="to" aria-label="Issue date To" defaultValue={values.to||""}/></label>
        <label className="min-w-0 text-[11px] font-medium text-slate-600">Sort<select className={input} name="sort" defaultValue={values.sort}>{Object.entries(reportSorts).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
        <div className="flex flex-wrap items-end gap-x-3 gap-y-2 @min-[680px]:flex-nowrap">
          <label className="flex h-8 shrink-0 items-center gap-1.5 whitespace-nowrap text-xs text-slate-700"><input type="checkbox" name="overdue" value="1" defaultChecked={values.overdue==="1"} className="size-3.5 accent-cyan-700"/>Overdue only</label>
          <button className={`h-8 rounded-md bg-slate-900 px-3 text-xs font-medium text-white ${focus}`}>Apply</button>
          <Link href="/invoices" className={`flex h-8 items-center whitespace-nowrap text-xs text-slate-600 hover:underline ${focus}`}>Clear filters</Link>
        </div>
      </div>
    </form>
    {customerMessage&&<p role="status" className="text-sm text-amber-800">{customerMessage}</p>}
    {message&&<div role="alert" className="rounded-xl border border-slate-200 bg-white p-5"><p className="font-medium">{message}</p><p className="mt-2 text-sm text-slate-600">Adjust the filters above or retry this view.</p><a href={reportUrl(values,Number(values.page)||1)} className={`mt-3 inline-block text-sm font-medium text-cyan-800 hover:underline ${focus}`}>Try again</a></div>}
    {report&&<>
      <section aria-label="Filtered invoice summary" className="grid grid-cols-2 rounded-lg border border-slate-200 bg-white @min-[680px]:grid-cols-4">{[["Invoice count",String(report.summary.invoice_count)],["Total invoiced",formatMoney(report.summary.total_invoiced)],["Amount paid",formatMoney(report.summary.amount_paid)],["Outstanding",formatMoney(report.summary.outstanding_balance)]].map(([label,value])=><div key={label} className="min-w-0 px-3 py-2.5"><h2 className="text-[11px] font-medium text-slate-500">{label}</h2><p className={`mt-0.5 break-words text-lg tabular-nums ${label==="Outstanding"?"font-bold":"font-medium"}`}>{value}</p></div>)}</section>
      <div className="flex flex-wrap justify-between gap-x-5 gap-y-1 text-[11px] leading-4 text-slate-500">
        <details className="min-w-0"><summary className={`w-fit cursor-pointer hover:text-slate-700 ${focus}`}>About these totals</summary><p className="mt-1 max-w-xl">{values.workflow==="void"?"Historical Void amounts. Outstanding is zero; these balances are not collectible.":"Totals cover all matching invoices. Void invoices count, but their financial amounts are excluded."}</p></details>
        <p>As of {formatBusinessDate(report.summary.resolved_as_of_date)} · New York</p>
      </div>
      {!report.rows.length?<div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-600">No invoices match these filters.</p><Link href="/invoices" className={`mt-2 inline-block text-sm font-medium text-cyan-800 hover:underline ${focus}`}>Clear filters</Link>{report.summary.total_rows>0&&<Link href={reportUrl(values)} className={`ml-4 text-sm font-medium text-cyan-800 hover:underline ${focus}`}>First page</Link>}</div>:<>
        <div className="hidden min-w-0 rounded-lg border border-slate-200 bg-white @min-[680px]:block"><table aria-label="Invoice list" className="w-full table-fixed text-left text-[11px] leading-4 @min-[900px]:text-xs"><caption className="sr-only">Invoices matching current filters</caption><colgroup><col className="w-[8%]"/><col className="w-[20%]"/><col className="w-[13%]"/><col className="w-[13%]"/><col className="w-[9%]"/><col className="w-[13%]"/><col className="w-[12%]"/><col className="w-[12%]"/></colgroup><thead className="border-b border-slate-200 text-slate-500"><tr>{["Invoice","Customer","Issue","Due","Workflow","Payment","Total","Balance"].map((label,i)=><th key={label} scope="col" className={`px-2 py-2 font-medium ${i>5?"text-right":""}`}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{report.rows.map(r=><tr key={r.invoice_id} className="h-12 align-middle hover:bg-slate-50"><td className="px-2 py-2"><Link className={`font-semibold text-cyan-800 hover:underline ${focus}`} href={`/invoices/${r.invoice_id}`}>#{r.invoice_number}</Link></td><td className="px-2 py-2"><Link className={`line-clamp-2 font-medium text-slate-900 hover:underline ${focus}`} href={`/invoices/${r.invoice_id}`}>{r.company_name_snapshot}</Link></td><td className="px-2 py-2 text-slate-600">{date(r.issue_date)}</td><td className="px-2 py-2 text-slate-600">{date(r.due_date)}{r.overdue&&<span className="mt-1 block font-medium text-amber-800">Overdue</span>}</td><td className="px-2 py-2"><span className="rounded bg-slate-100 px-1.5 py-0.5 text-slate-700">{workflowLabel(r.workflow_status)}</span></td><td className="px-2 py-2 text-slate-600">{paymentLabel(r.payment_status)}</td><td className="px-2 py-2 text-right tabular-nums">{formatMoney(r.invoice_total)}</td><td className="px-2 py-2 text-right font-semibold tabular-nums">{formatMoney(r.balance_due)}</td></tr>)}</tbody></table></div>
        <ul aria-label="Invoice cards" className="space-y-3 @min-[680px]:hidden">{report.rows.map(r=><li key={r.invoice_id}><Link href={`/invoices/${r.invoice_id}`} className={`block rounded-xl border border-slate-200 bg-white p-4 hover:border-slate-300 ${focus}`}><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><p className="font-semibold">Invoice #{r.invoice_number}</p><p className="mt-1 text-sm text-slate-700">{r.company_name_snapshot}</p></div>{r.overdue&&<span className="rounded bg-amber-50 px-2 py-1 text-xs font-medium text-amber-800">Overdue</span>}</div><p className="mt-3 text-xs text-slate-600">{workflowLabel(r.workflow_status)} · {paymentLabel(r.payment_status)}</p><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate-500">Issue date</dt><dd className="mt-1">{date(r.issue_date)}</dd></div><div><dt className="text-xs text-slate-500">Due date</dt><dd className="mt-1">{date(r.due_date)}</dd></div></dl><dl className="mt-3 space-y-2 border-t border-slate-100 pt-3 text-sm tabular-nums"><div className="flex justify-between gap-3"><dt className="text-slate-500">Total</dt><dd className="min-w-0 text-right">{formatMoney(r.invoice_total)}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Balance</dt><dd className="min-w-0 text-right font-semibold">{formatMoney(r.balance_due)}</dd></div></dl></Link></li>)}</ul>
      </>}
      <nav aria-label="Invoice pages" className="flex flex-wrap items-center justify-between gap-3 pt-0.5 text-xs"><p className="text-xs text-slate-500">Showing {report.rows.length?(report.summary.page-1)*report.summary.page_size+1:0}–{report.rows.length?(report.summary.page-1)*report.summary.page_size+report.rows.length:0} of {report.summary.total_rows}{report.summary.total_pages>0&&` · Page ${report.summary.page} of ${report.summary.total_pages}`}</p><div className="flex gap-5">{report.summary.page>1&&<Link className={`font-medium text-cyan-800 hover:underline ${focus}`} href={reportUrl(values,report.summary.page-1)}>Previous</Link>}{report.summary.page<report.summary.total_pages&&<Link className={`font-medium text-cyan-800 hover:underline ${focus}`} href={reportUrl(values,report.summary.page+1)}>Next</Link>}</div></nav>
    </>}
  </div>;
}
