import Link from "next/link";
import type { getPaymentReport } from "@/lib/payments/report-server";
import { paymentReportUrl } from "@/lib/payments/report";
import { paymentMethods } from "@/lib/payments/model";
import { formatMoney,formatBusinessDate } from "@/lib/billing/model";
const input="mt-1 block h-9 w-full min-w-0 rounded-lg border border-slate-300 bg-white px-2 text-xs";
const link="font-medium text-cyan-800 hover:underline focus-visible:outline-cyan-700";
export function PaymentReportView({data}:{data:Awaited<ReturnType<typeof getPaymentReport>>}) {
  const {filters:{values},customers,customerMessage,report,message}=data;
  return <div className="@container min-w-0 space-y-4 [overflow-wrap:anywhere]">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Payments</h1><p className="mt-2 text-sm text-slate-600">Recorded receipts and payment history.</p></div><Link href="/payments/new" className="rounded-lg bg-cyan-400 px-4 py-2.5 text-sm font-semibold">Record Payment</Link></header>
    <form key={paymentReportUrl(values,Number(values.page)||1)} action="/payments" method="get" aria-label="Payment filters" className="rounded-lg border border-slate-200 bg-white p-3">
      <div className="grid gap-3 sm:grid-cols-2 @min-[800px]:grid-cols-4">
        <label className="min-w-0 text-xs font-medium">Search<input className={input} name="q" type="search" maxLength={500} defaultValue={values.q} placeholder="Invoice #, customer or reference"/></label>
        <label className="min-w-0 text-xs font-medium">Customer<select className={input} name="customer" defaultValue={values.customer}><option value="">All customers</option>{values.customer&&!customers.some(c=>c.id===values.customer)&&<option value={values.customer}>Selected customer unavailable</option>}{customers.map(c=><option key={c.id} value={c.id}>{c.company_name}{c.is_active?"":" (Archived)"}</option>)}</select></label>
        <label className="min-w-0 text-xs font-medium">Method<select className={input} name="method" defaultValue={values.method}><option value="">All methods</option>{Object.entries(paymentMethods).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
        <label className="min-w-0 text-xs font-medium">Payment status<select className={input} name="status" defaultValue={values.status}><option value="active">Active</option><option value="voided">Voided</option><option value="all">All payments</option></select></label>
      </div>
      <div className="mt-3 grid items-end gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className="text-xs font-medium">Payment date From<input className={input} name="from" type="date" defaultValue={values.from}/></label><label className="text-xs font-medium">Payment date To<input className={input} name="to" type="date" defaultValue={values.to}/></label><div className="flex h-9 items-center gap-4"><button className="rounded-lg bg-slate-900 px-4 py-2 text-xs font-medium text-white">Apply</button><Link className={`${link} text-xs`} href="/payments">Clear filters</Link></div></div>
    </form>
    {customerMessage&&<p role="status" className="text-sm text-amber-800">{customerMessage}</p>}
    {message&&<div role="alert" className="rounded-lg border border-slate-200 bg-white p-5"><p>{message}</p><a className={`${link} mt-3 inline-block text-sm`} href={paymentReportUrl(values,Number(values.page)||1)}>Try again</a></div>}
    {report&&<>
      <section aria-label="Filtered payment summary" className="grid gap-px overflow-hidden rounded-lg border border-slate-200 bg-slate-200 sm:grid-cols-3">{[["Payments Received",formatMoney(report.summary.payments_received)],["Payment Count",String(report.summary.payment_count)],["Average Payment",formatMoney(report.summary.average_payment)]].map(([label,value])=><div key={label} className="min-w-0 bg-white p-4"><h2 className="text-xs font-medium text-slate-500">{label}</h2><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p></div>)}</section>
      <p className="text-xs leading-5 text-slate-500">Payment dates: {values.from?formatBusinessDate(values.from):"All earlier dates"} – {values.to?formatBusinessDate(values.to):"All later dates"}. Totals include all matching active receipts, excluding voided payments and payments on Void invoices. These are receipts, not invoice totals or outstanding balances.</p>
      <p className="text-xs text-slate-500">For a correction, open an invoice’s payment history to void and replace the payment.</p>
      {!report.rows.length?<div className="rounded-lg border border-slate-200 bg-white p-5 text-sm">No payments match this view. {report.summary.total_rows>0&&<Link className={link} href={paymentReportUrl(values)}>First page</Link>}</div>:<>
        <div className="hidden rounded-lg border border-slate-200 bg-white @min-[780px]:block"><table className="w-full table-fixed text-left text-xs" aria-label="Payment ledger"><thead className="border-b border-slate-200 text-slate-500"><tr>{["Payment date","Customer","Invoice","Amount","Method","Reference","Status"].map(label=><th className="px-3 py-3 font-medium" scope="col" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{report.rows.map(r=><tr key={r.payment_id} className="hover:bg-slate-50"><td className="px-3 py-3">{formatBusinessDate(r.payment_date)}</td><td className="px-3 py-3"><Link className={link} href={`/customers/${r.customer_id}`}>{r.company_name_snapshot}</Link></td><td className="px-3 py-3"><Link className={link} href={`/invoices/${r.invoice_id}#payment-history`}>#{r.invoice_number}</Link></td><td className="px-3 py-3 tabular-nums">{formatMoney(r.amount)}</td><td className="px-3 py-3">{paymentMethods[r.payment_method as keyof typeof paymentMethods]}</td><td className="px-3 py-3">{r.reference||"—"}</td><td className="px-3 py-3"><span>{r.payment_status==="active"?"Active":"Voided"}</span>{r.invoice_status==="void"&&<span className="mt-1 block font-medium text-rose-800">Invoice Void</span>}</td></tr>)}</tbody></table></div>
        <ul aria-label="Payment cards" className="space-y-3 @min-[780px]:hidden">{report.rows.map(r=><li key={r.payment_id} className="rounded-lg border border-slate-200 bg-white p-4 text-sm"><div className="flex justify-between gap-3"><Link className={link} href={`/customers/${r.customer_id}`}>{r.company_name_snapshot}</Link><span className="font-semibold tabular-nums">{formatMoney(r.amount)}</span></div><Link className={`${link} mt-2 inline-block`} href={`/invoices/${r.invoice_id}#payment-history`}>Invoice #{r.invoice_number} · Payment history</Link><p className="mt-2 text-xs text-slate-600">{formatBusinessDate(r.payment_date)} · {paymentMethods[r.payment_method as keyof typeof paymentMethods]} · {r.payment_status==="active"?"Active":"Voided"}</p>{r.reference&&<p className="mt-2 text-xs">Reference: {r.reference}</p>}{r.invoice_status==="void"&&<p className="mt-2 text-xs font-medium text-rose-800">Invoice Void</p>}</li>)}</ul>
      </>}
      <nav aria-label="Payment pages" className="flex flex-wrap justify-between gap-3 text-xs"><p className="text-slate-500">{report.summary.total_rows} ledger records{report.summary.total_pages>0&&` · Page ${report.summary.page} of ${report.summary.total_pages}`}</p><div className="flex gap-5">{report.summary.page>1&&<Link className={link} href={paymentReportUrl(values,report.summary.page-1)}>Previous</Link>}{report.summary.page<report.summary.total_pages&&<Link className={link} href={paymentReportUrl(values,report.summary.page+1)}>Next</Link>}</div></nav>
    </>}
  </div>;
}
